@startuml

title Sending data from Node A to Node D over multi hop route

== Create Control Channels ==

"Node A" -> "Node B": Send "CreateControlChannel" message\n- over temporary route "A:B"
"Node B" --> "Node A": Reply with new Channel ID: "Foo"
|||
"Node A" -> "Node C": Send "CreateControlChannel" message\n- over temporary route "A:C"
"Node C" --> "Node A": Reply with new Channel ID: "Bar"

== Setup routes using Control Messages ==

"Node A" -> "Node A": Create new multi hop route\nwith ID "MHR" and set first hop as A:B
|||
"Node A" -> "Node B": Send control message "SetRoute"\n- over route: A:B\n- control channel: Foo\n- route: MHR\n- forward: Node C\n- reply: Node A
"Node B" -> "Node B": Route table update
"Node B" --> "Node A": Reply OK
|||
"Node A" -> "Node C": Send control message "SetRoute" \n- over route: A:C\n- control channel: Bar\n- route: MHR\n- forward: Node D\n- reply: Node A
"Node C" -> "Node C": Route table update
"Node C" --> "Node A": Reply OK

== Send user data through route ==

"Node A" -> "Node B": Send user message\n- over route "MHR"
"Node B" --> "Node A": Reply ACK
"Node B" -> "Node B": Route table lookup:\nforwarding rule found
"Node B" -> "Node C": Forward user message\n- over route "MHR"
"Node C" --> "Node B": Reply ACK
"Node C" -> "Node C": Route table lookup:\nforwarding rule found
"Node C" -> "Node D": Forward user message\n- over route "MHR"
"Node D" -> "Node D": Route table lookup:\nnowhere to forward!
"Node D" ->: Receive user message

== Remove routes using Control Messages ==

"Node A" -> "Node B": Send control message "RemoveRoute" \n- control channel: Foo\n- route: MHR
"Node B" -> "Node B": Route table update
"Node B" --> "Node A": Reply OK
|||
"Node A" -> "Node C": Send control message "RemoveRoute" \n- control channel: Bar\n- route: MHR
"Node C" -> "Node C": Route table update
"Node C" --> "Node A": Reply OK

== Close Control Channels ==

"Node A" -> "Node B": Send "CloseControlChannel" message
"Node B" --> "Node A": Reply OK
|||
"Node A" -> "Node C": Send "CloseControlChannel" message
"Node C" --> "Node A": Reply OK


@enduml
