// Code generated by github.com/skycoin/skyencoder. DO NOT EDIT.
package coin

import "github.com/skycoin/skycoin/src/cipher/encoder"

// encodeSizeUxHead computes the size of an encoded object of type UxHead
func encodeSizeUxHead(obj *UxHead) uint64 {
	i0 := uint64(0)

	// obj.Time
	i0 += 8

	// obj.BkSeq
	i0 += 8

	return i0
}

// encodeUxHead encodes an object of type UxHead to the buffer in encoder.Encoder.
// The buffer must be large enough to encode the object, otherwise an error is returned.
func encodeUxHead(buf []byte, obj *UxHead) error {
	e := &encoder.Encoder{
		Buffer: buf[:],
	}

	// obj.Time
	e.Uint64(obj.Time)

	// obj.BkSeq
	e.Uint64(obj.BkSeq)

	return nil
}

// decodeUxHead decodes an object of type UxHead from the buffer in encoder.Decoder.
// Returns the number of bytes used from the buffer to decode the object.
func decodeUxHead(buf []byte, obj *UxHead) (int, error) {
	d := &encoder.Decoder{
		Buffer: buf[:],
	}

	{
		// obj.Time
		i, err := d.Uint64()
		if err != nil {
			return len(buf) - len(d.Buffer), err
		}
		obj.Time = i
	}

	{
		// obj.BkSeq
		i, err := d.Uint64()
		if err != nil {
			return len(buf) - len(d.Buffer), err
		}
		obj.BkSeq = i
	}

	return len(buf) - len(d.Buffer), nil
}
