// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto
	types.proto

It has these top-level messages:
	Initialize
	GetFeatures
	Features
	SetMnemonic
	ChangePin
	SkycoinAddress
	ResponseSkycoinAddress
	SkycoinCheckMessageSignature
	SkycoinSignMessage
	Ping
	Success
	Failure
	ButtonRequest
	ButtonAck
	PinMatrixRequest
	PinMatrixAck
	Cancel
	PassphraseRequest
	PassphraseAck
	PassphraseStateRequest
	PassphraseStateAck
	GetEntropy
	Entropy
	WipeDevice
	LoadDevice
	ResetDevice
	BackupDevice
	EntropyRequest
	EntropyAck
	HDNodeType
	HDNodePathType
	CoinType
	MultisigRedeemScriptType
	TxInputType
	TxOutputType
	TxOutputBinType
	TransactionType
	TxRequestDetailsType
	TxRequestSerializedType
	IdentityType
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Mapping between Trezor wire identifier (uint) and a protobuf message
type MessageType int32

const (
	MessageType_MessageType_Initialize                   MessageType = 0
	MessageType_MessageType_Ping                         MessageType = 1
	MessageType_MessageType_Success                      MessageType = 2
	MessageType_MessageType_Failure                      MessageType = 3
	MessageType_MessageType_ChangePin                    MessageType = 4
	MessageType_MessageType_WipeDevice                   MessageType = 5
	MessageType_MessageType_GetEntropy                   MessageType = 9
	MessageType_MessageType_Entropy                      MessageType = 10
	MessageType_MessageType_LoadDevice                   MessageType = 13
	MessageType_MessageType_ResetDevice                  MessageType = 14
	MessageType_MessageType_Features                     MessageType = 17
	MessageType_MessageType_PinMatrixRequest             MessageType = 18
	MessageType_MessageType_PinMatrixAck                 MessageType = 19
	MessageType_MessageType_Cancel                       MessageType = 20
	MessageType_MessageType_ButtonRequest                MessageType = 26
	MessageType_MessageType_ButtonAck                    MessageType = 27
	MessageType_MessageType_BackupDevice                 MessageType = 34
	MessageType_MessageType_EntropyRequest               MessageType = 35
	MessageType_MessageType_EntropyAck                   MessageType = 36
	MessageType_MessageType_PassphraseRequest            MessageType = 41
	MessageType_MessageType_PassphraseAck                MessageType = 42
	MessageType_MessageType_PassphraseStateRequest       MessageType = 77
	MessageType_MessageType_PassphraseStateAck           MessageType = 78
	MessageType_MessageType_SetMnemonic                  MessageType = 113
	MessageType_MessageType_SkycoinAddress               MessageType = 114
	MessageType_MessageType_SkycoinCheckMessageSignature MessageType = 115
	MessageType_MessageType_SkycoinSignMessage           MessageType = 116
	MessageType_MessageType_ResponseSkycoinAddress       MessageType = 117
)

var MessageType_name = map[int32]string{
	0:   "MessageType_Initialize",
	1:   "MessageType_Ping",
	2:   "MessageType_Success",
	3:   "MessageType_Failure",
	4:   "MessageType_ChangePin",
	5:   "MessageType_WipeDevice",
	9:   "MessageType_GetEntropy",
	10:  "MessageType_Entropy",
	13:  "MessageType_LoadDevice",
	14:  "MessageType_ResetDevice",
	17:  "MessageType_Features",
	18:  "MessageType_PinMatrixRequest",
	19:  "MessageType_PinMatrixAck",
	20:  "MessageType_Cancel",
	26:  "MessageType_ButtonRequest",
	27:  "MessageType_ButtonAck",
	34:  "MessageType_BackupDevice",
	35:  "MessageType_EntropyRequest",
	36:  "MessageType_EntropyAck",
	41:  "MessageType_PassphraseRequest",
	42:  "MessageType_PassphraseAck",
	77:  "MessageType_PassphraseStateRequest",
	78:  "MessageType_PassphraseStateAck",
	113: "MessageType_SetMnemonic",
	114: "MessageType_SkycoinAddress",
	115: "MessageType_SkycoinCheckMessageSignature",
	116: "MessageType_SkycoinSignMessage",
	117: "MessageType_ResponseSkycoinAddress",
}
var MessageType_value = map[string]int32{
	"MessageType_Initialize":                   0,
	"MessageType_Ping":                         1,
	"MessageType_Success":                      2,
	"MessageType_Failure":                      3,
	"MessageType_ChangePin":                    4,
	"MessageType_WipeDevice":                   5,
	"MessageType_GetEntropy":                   9,
	"MessageType_Entropy":                      10,
	"MessageType_LoadDevice":                   13,
	"MessageType_ResetDevice":                  14,
	"MessageType_Features":                     17,
	"MessageType_PinMatrixRequest":             18,
	"MessageType_PinMatrixAck":                 19,
	"MessageType_Cancel":                       20,
	"MessageType_ButtonRequest":                26,
	"MessageType_ButtonAck":                    27,
	"MessageType_BackupDevice":                 34,
	"MessageType_EntropyRequest":               35,
	"MessageType_EntropyAck":                   36,
	"MessageType_PassphraseRequest":            41,
	"MessageType_PassphraseAck":                42,
	"MessageType_PassphraseStateRequest":       77,
	"MessageType_PassphraseStateAck":           78,
	"MessageType_SetMnemonic":                  113,
	"MessageType_SkycoinAddress":               114,
	"MessageType_SkycoinCheckMessageSignature": 115,
	"MessageType_SkycoinSignMessage":           116,
	"MessageType_ResponseSkycoinAddress":       117,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// *
// Request: Reset device to default state and ask for device details
// @next Features
type Initialize struct {
	State            []byte `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Initialize) Reset()                    { *m = Initialize{} }
func (m *Initialize) String() string            { return proto.CompactTextString(m) }
func (*Initialize) ProtoMessage()               {}
func (*Initialize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Initialize) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

// *
// Request: Ask for device details (no device reset)
// @next Features
type GetFeatures struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetFeatures) Reset()                    { *m = GetFeatures{} }
func (m *GetFeatures) String() string            { return proto.CompactTextString(m) }
func (*GetFeatures) ProtoMessage()               {}
func (*GetFeatures) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// *
// Response: Reports various information about the device
// @prev Initialize
// @prev GetFeatures
type Features struct {
	Vendor               *string     `protobuf:"bytes,1,opt,name=vendor" json:"vendor,omitempty"`
	MajorVersion         *uint32     `protobuf:"varint,2,opt,name=major_version,json=majorVersion" json:"major_version,omitempty"`
	MinorVersion         *uint32     `protobuf:"varint,3,opt,name=minor_version,json=minorVersion" json:"minor_version,omitempty"`
	PatchVersion         *uint32     `protobuf:"varint,4,opt,name=patch_version,json=patchVersion" json:"patch_version,omitempty"`
	BootloaderMode       *bool       `protobuf:"varint,5,opt,name=bootloader_mode,json=bootloaderMode" json:"bootloader_mode,omitempty"`
	DeviceId             *string     `protobuf:"bytes,6,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	PinProtection        *bool       `protobuf:"varint,7,opt,name=pin_protection,json=pinProtection" json:"pin_protection,omitempty"`
	PassphraseProtection *bool       `protobuf:"varint,8,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	Language             *string     `protobuf:"bytes,9,opt,name=language" json:"language,omitempty"`
	Label                *string     `protobuf:"bytes,10,opt,name=label" json:"label,omitempty"`
	Coins                []*CoinType `protobuf:"bytes,11,rep,name=coins" json:"coins,omitempty"`
	Initialized          *bool       `protobuf:"varint,12,opt,name=initialized" json:"initialized,omitempty"`
	Revision             []byte      `protobuf:"bytes,13,opt,name=revision" json:"revision,omitempty"`
	BootloaderHash       []byte      `protobuf:"bytes,14,opt,name=bootloader_hash,json=bootloaderHash" json:"bootloader_hash,omitempty"`
	Imported             *bool       `protobuf:"varint,15,opt,name=imported" json:"imported,omitempty"`
	PinCached            *bool       `protobuf:"varint,16,opt,name=pin_cached,json=pinCached" json:"pin_cached,omitempty"`
	PassphraseCached     *bool       `protobuf:"varint,17,opt,name=passphrase_cached,json=passphraseCached" json:"passphrase_cached,omitempty"`
	FirmwarePresent      *bool       `protobuf:"varint,18,opt,name=firmware_present,json=firmwarePresent" json:"firmware_present,omitempty"`
	NeedsBackup          *bool       `protobuf:"varint,19,opt,name=needs_backup,json=needsBackup" json:"needs_backup,omitempty"`
	Flags                *uint32     `protobuf:"varint,20,opt,name=flags" json:"flags,omitempty"`
	Model                *string     `protobuf:"bytes,21,opt,name=model" json:"model,omitempty"`
	FwMajor              *uint32     `protobuf:"varint,22,opt,name=fw_major,json=fwMajor" json:"fw_major,omitempty"`
	FwMinor              *uint32     `protobuf:"varint,23,opt,name=fw_minor,json=fwMinor" json:"fw_minor,omitempty"`
	FwPatch              *uint32     `protobuf:"varint,24,opt,name=fw_patch,json=fwPatch" json:"fw_patch,omitempty"`
	FwVendor             *string     `protobuf:"bytes,25,opt,name=fw_vendor,json=fwVendor" json:"fw_vendor,omitempty"`
	FwVendorKeys         []byte      `protobuf:"bytes,26,opt,name=fw_vendor_keys,json=fwVendorKeys" json:"fw_vendor_keys,omitempty"`
	UnfinishedBackup     *bool       `protobuf:"varint,27,opt,name=unfinished_backup,json=unfinishedBackup" json:"unfinished_backup,omitempty"`
	XXX_unrecognized     []byte      `json:"-"`
}

func (m *Features) Reset()                    { *m = Features{} }
func (m *Features) String() string            { return proto.CompactTextString(m) }
func (*Features) ProtoMessage()               {}
func (*Features) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Features) GetVendor() string {
	if m != nil && m.Vendor != nil {
		return *m.Vendor
	}
	return ""
}

func (m *Features) GetMajorVersion() uint32 {
	if m != nil && m.MajorVersion != nil {
		return *m.MajorVersion
	}
	return 0
}

func (m *Features) GetMinorVersion() uint32 {
	if m != nil && m.MinorVersion != nil {
		return *m.MinorVersion
	}
	return 0
}

func (m *Features) GetPatchVersion() uint32 {
	if m != nil && m.PatchVersion != nil {
		return *m.PatchVersion
	}
	return 0
}

func (m *Features) GetBootloaderMode() bool {
	if m != nil && m.BootloaderMode != nil {
		return *m.BootloaderMode
	}
	return false
}

func (m *Features) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *Features) GetPinProtection() bool {
	if m != nil && m.PinProtection != nil {
		return *m.PinProtection
	}
	return false
}

func (m *Features) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

func (m *Features) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *Features) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Features) GetCoins() []*CoinType {
	if m != nil {
		return m.Coins
	}
	return nil
}

func (m *Features) GetInitialized() bool {
	if m != nil && m.Initialized != nil {
		return *m.Initialized
	}
	return false
}

func (m *Features) GetRevision() []byte {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *Features) GetBootloaderHash() []byte {
	if m != nil {
		return m.BootloaderHash
	}
	return nil
}

func (m *Features) GetImported() bool {
	if m != nil && m.Imported != nil {
		return *m.Imported
	}
	return false
}

func (m *Features) GetPinCached() bool {
	if m != nil && m.PinCached != nil {
		return *m.PinCached
	}
	return false
}

func (m *Features) GetPassphraseCached() bool {
	if m != nil && m.PassphraseCached != nil {
		return *m.PassphraseCached
	}
	return false
}

func (m *Features) GetFirmwarePresent() bool {
	if m != nil && m.FirmwarePresent != nil {
		return *m.FirmwarePresent
	}
	return false
}

func (m *Features) GetNeedsBackup() bool {
	if m != nil && m.NeedsBackup != nil {
		return *m.NeedsBackup
	}
	return false
}

func (m *Features) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *Features) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *Features) GetFwMajor() uint32 {
	if m != nil && m.FwMajor != nil {
		return *m.FwMajor
	}
	return 0
}

func (m *Features) GetFwMinor() uint32 {
	if m != nil && m.FwMinor != nil {
		return *m.FwMinor
	}
	return 0
}

func (m *Features) GetFwPatch() uint32 {
	if m != nil && m.FwPatch != nil {
		return *m.FwPatch
	}
	return 0
}

func (m *Features) GetFwVendor() string {
	if m != nil && m.FwVendor != nil {
		return *m.FwVendor
	}
	return ""
}

func (m *Features) GetFwVendorKeys() []byte {
	if m != nil {
		return m.FwVendorKeys
	}
	return nil
}

func (m *Features) GetUnfinishedBackup() bool {
	if m != nil && m.UnfinishedBackup != nil {
		return *m.UnfinishedBackup
	}
	return false
}

// *
// Request: Send a mnemonic to the device
// @next Success
type SetMnemonic struct {
	Mnemonic         *string `protobuf:"bytes,1,req,name=mnemonic" json:"mnemonic,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetMnemonic) Reset()                    { *m = SetMnemonic{} }
func (m *SetMnemonic) String() string            { return proto.CompactTextString(m) }
func (*SetMnemonic) ProtoMessage()               {}
func (*SetMnemonic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SetMnemonic) GetMnemonic() string {
	if m != nil && m.Mnemonic != nil {
		return *m.Mnemonic
	}
	return ""
}

// *
// Request: Starts workflow for setting/changing/removing the PIN
// @next ButtonRequest
// @next PinMatrixRequest
type ChangePin struct {
	Remove           *bool  `protobuf:"varint,1,opt,name=remove" json:"remove,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChangePin) Reset()                    { *m = ChangePin{} }
func (m *ChangePin) String() string            { return proto.CompactTextString(m) }
func (*ChangePin) ProtoMessage()               {}
func (*ChangePin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChangePin) GetRemove() bool {
	if m != nil && m.Remove != nil {
		return *m.Remove
	}
	return false
}

// *
// Request: Generate a Skycoin or a Bitcoin address from a seed, device sends back the address in a Success message
// @next Failure
// @next ResponseSkycoinAddress
type SkycoinAddress struct {
	AddressN *uint32 `protobuf:"varint,1,req,name=address_n,json=addressN" json:"address_n,omitempty"`
	// required string seed = 1; // seed used to generate address
	AddressType      *SkycoinAddressType `protobuf:"varint,2,opt,name=address_type,json=addressType,enum=SkycoinAddressType" json:"address_type,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *SkycoinAddress) Reset()                    { *m = SkycoinAddress{} }
func (m *SkycoinAddress) String() string            { return proto.CompactTextString(m) }
func (*SkycoinAddress) ProtoMessage()               {}
func (*SkycoinAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SkycoinAddress) GetAddressN() uint32 {
	if m != nil && m.AddressN != nil {
		return *m.AddressN
	}
	return 0
}

func (m *SkycoinAddress) GetAddressType() SkycoinAddressType {
	if m != nil && m.AddressType != nil {
		return *m.AddressType
	}
	return SkycoinAddressType_AddressTypeSkycoin
}

// *
// Response: Return the generated skycoin address
// @prev SkycoinAddress
type ResponseSkycoinAddress struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseSkycoinAddress) Reset()                    { *m = ResponseSkycoinAddress{} }
func (m *ResponseSkycoinAddress) String() string            { return proto.CompactTextString(m) }
func (*ResponseSkycoinAddress) ProtoMessage()               {}
func (*ResponseSkycoinAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResponseSkycoinAddress) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

// *
// Request: Check a message signature matches the given address.
// @next Success
type SkycoinCheckMessageSignature struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Message          *string `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Signature        *string `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SkycoinCheckMessageSignature) Reset()                    { *m = SkycoinCheckMessageSignature{} }
func (m *SkycoinCheckMessageSignature) String() string            { return proto.CompactTextString(m) }
func (*SkycoinCheckMessageSignature) ProtoMessage()               {}
func (*SkycoinCheckMessageSignature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SkycoinCheckMessageSignature) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *SkycoinCheckMessageSignature) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *SkycoinCheckMessageSignature) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

// *
// Request: Sign a message digest using the given secret key.
// @next Success
type SkycoinSignMessage struct {
	AddressN         *uint32 `protobuf:"varint,1,req,name=address_n,json=addressN" json:"address_n,omitempty"`
	Message          *string `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SkycoinSignMessage) Reset()                    { *m = SkycoinSignMessage{} }
func (m *SkycoinSignMessage) String() string            { return proto.CompactTextString(m) }
func (*SkycoinSignMessage) ProtoMessage()               {}
func (*SkycoinSignMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SkycoinSignMessage) GetAddressN() uint32 {
	if m != nil && m.AddressN != nil {
		return *m.AddressN
	}
	return 0
}

func (m *SkycoinSignMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// *
// Request: Test if the device is alive, device sends back the message in Success response
// @next Success
type Ping struct {
	Message              *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	ButtonProtection     *bool   `protobuf:"varint,2,opt,name=button_protection,json=buttonProtection" json:"button_protection,omitempty"`
	PinProtection        *bool   `protobuf:"varint,3,opt,name=pin_protection,json=pinProtection" json:"pin_protection,omitempty"`
	PassphraseProtection *bool   `protobuf:"varint,4,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Ping) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Ping) GetButtonProtection() bool {
	if m != nil && m.ButtonProtection != nil {
		return *m.ButtonProtection
	}
	return false
}

func (m *Ping) GetPinProtection() bool {
	if m != nil && m.PinProtection != nil {
		return *m.PinProtection
	}
	return false
}

func (m *Ping) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

// *
// Response: Success of the previous request
type Success struct {
	Message          *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Success) Reset()                    { *m = Success{} }
func (m *Success) String() string            { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()               {}
func (*Success) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Success) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// *
// Response: Failure of the previous request
type Failure struct {
	Code             *FailureType `protobuf:"varint,1,opt,name=code,enum=FailureType" json:"code,omitempty"`
	Message          *string      `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Failure) Reset()                    { *m = Failure{} }
func (m *Failure) String() string            { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()               {}
func (*Failure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Failure) GetCode() FailureType {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return FailureType_Failure_UnexpectedMessage
}

func (m *Failure) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// *
// Response: Device is waiting for HW button press.
// @next ButtonAck
// @next Cancel
type ButtonRequest struct {
	Code             *ButtonRequestType `protobuf:"varint,1,opt,name=code,enum=ButtonRequestType" json:"code,omitempty"`
	Data             *string            `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ButtonRequest) Reset()                    { *m = ButtonRequest{} }
func (m *ButtonRequest) String() string            { return proto.CompactTextString(m) }
func (*ButtonRequest) ProtoMessage()               {}
func (*ButtonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ButtonRequest) GetCode() ButtonRequestType {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ButtonRequestType_ButtonRequest_Other
}

func (m *ButtonRequest) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

// *
// Request: Computer agrees to wait for HW button press
// @prev ButtonRequest
type ButtonAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ButtonAck) Reset()                    { *m = ButtonAck{} }
func (m *ButtonAck) String() string            { return proto.CompactTextString(m) }
func (*ButtonAck) ProtoMessage()               {}
func (*ButtonAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// *
// Response: Device is asking computer to show PIN matrix and awaits PIN encoded using this matrix scheme
// @next PinMatrixAck
// @next Cancel
type PinMatrixRequest struct {
	Type             *PinMatrixRequestType `protobuf:"varint,1,opt,name=type,enum=PinMatrixRequestType" json:"type,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PinMatrixRequest) Reset()                    { *m = PinMatrixRequest{} }
func (m *PinMatrixRequest) String() string            { return proto.CompactTextString(m) }
func (*PinMatrixRequest) ProtoMessage()               {}
func (*PinMatrixRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PinMatrixRequest) GetType() PinMatrixRequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PinMatrixRequestType_PinMatrixRequestType_Current
}

// *
// Request: Computer responds with encoded PIN
// @prev PinMatrixRequest
type PinMatrixAck struct {
	Pin              *string `protobuf:"bytes,1,req,name=pin" json:"pin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PinMatrixAck) Reset()                    { *m = PinMatrixAck{} }
func (m *PinMatrixAck) String() string            { return proto.CompactTextString(m) }
func (*PinMatrixAck) ProtoMessage()               {}
func (*PinMatrixAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PinMatrixAck) GetPin() string {
	if m != nil && m.Pin != nil {
		return *m.Pin
	}
	return ""
}

// *
// Request: Abort last operation that required user interaction
// @prev ButtonRequest
// @prev PinMatrixRequest
// @prev PassphraseRequest
type Cancel struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Cancel) Reset()                    { *m = Cancel{} }
func (m *Cancel) String() string            { return proto.CompactTextString(m) }
func (*Cancel) ProtoMessage()               {}
func (*Cancel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

// *
// Response: Device awaits encryption passphrase
// @next PassphraseAck
// @next Cancel
type PassphraseRequest struct {
	OnDevice         *bool  `protobuf:"varint,1,opt,name=on_device,json=onDevice" json:"on_device,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PassphraseRequest) Reset()                    { *m = PassphraseRequest{} }
func (m *PassphraseRequest) String() string            { return proto.CompactTextString(m) }
func (*PassphraseRequest) ProtoMessage()               {}
func (*PassphraseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PassphraseRequest) GetOnDevice() bool {
	if m != nil && m.OnDevice != nil {
		return *m.OnDevice
	}
	return false
}

// *
// Request: Send passphrase back
// @prev PassphraseRequest
// @next PassphraseStateRequest
type PassphraseAck struct {
	Passphrase       *string `protobuf:"bytes,1,opt,name=passphrase" json:"passphrase,omitempty"`
	State            []byte  `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PassphraseAck) Reset()                    { *m = PassphraseAck{} }
func (m *PassphraseAck) String() string            { return proto.CompactTextString(m) }
func (*PassphraseAck) ProtoMessage()               {}
func (*PassphraseAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PassphraseAck) GetPassphrase() string {
	if m != nil && m.Passphrase != nil {
		return *m.Passphrase
	}
	return ""
}

func (m *PassphraseAck) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

// *
// @prev PassphraseAck
// @next PassphraseStateAck
type PassphraseStateRequest struct {
	State            []byte `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PassphraseStateRequest) Reset()                    { *m = PassphraseStateRequest{} }
func (m *PassphraseStateRequest) String() string            { return proto.CompactTextString(m) }
func (*PassphraseStateRequest) ProtoMessage()               {}
func (*PassphraseStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PassphraseStateRequest) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

// *
// @prev PassphraseStateRequest
type PassphraseStateAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PassphraseStateAck) Reset()                    { *m = PassphraseStateAck{} }
func (m *PassphraseStateAck) String() string            { return proto.CompactTextString(m) }
func (*PassphraseStateAck) ProtoMessage()               {}
func (*PassphraseStateAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

// *
// Request: Request a sample of random data generated by hardware RNG. May be used for testing.
// @next ButtonRequest
// @next Entropy
// @next Failure
type GetEntropy struct {
	Size             *uint32 `protobuf:"varint,1,req,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetEntropy) Reset()                    { *m = GetEntropy{} }
func (m *GetEntropy) String() string            { return proto.CompactTextString(m) }
func (*GetEntropy) ProtoMessage()               {}
func (*GetEntropy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetEntropy) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

// *
// Response: Reply with random data generated by internal RNG
// @prev GetEntropy
type Entropy struct {
	Entropy          []byte `protobuf:"bytes,1,req,name=entropy" json:"entropy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Entropy) Reset()                    { *m = Entropy{} }
func (m *Entropy) String() string            { return proto.CompactTextString(m) }
func (*Entropy) ProtoMessage()               {}
func (*Entropy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Entropy) GetEntropy() []byte {
	if m != nil {
		return m.Entropy
	}
	return nil
}

// *
// Request: Request device to wipe all sensitive data and settings
// @next ButtonRequest
type WipeDevice struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *WipeDevice) Reset()                    { *m = WipeDevice{} }
func (m *WipeDevice) String() string            { return proto.CompactTextString(m) }
func (*WipeDevice) ProtoMessage()               {}
func (*WipeDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

// *
// Request: Load seed and related internal settings from the computer
// @next ButtonRequest
// @next Success
// @next Failure
type LoadDevice struct {
	Mnemonic             *string     `protobuf:"bytes,1,opt,name=mnemonic" json:"mnemonic,omitempty"`
	Node                 *HDNodeType `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
	Pin                  *string     `protobuf:"bytes,3,opt,name=pin" json:"pin,omitempty"`
	PassphraseProtection *bool       `protobuf:"varint,4,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	Language             *string     `protobuf:"bytes,5,opt,name=language,def=english" json:"language,omitempty"`
	Label                *string     `protobuf:"bytes,6,opt,name=label" json:"label,omitempty"`
	SkipChecksum         *bool       `protobuf:"varint,7,opt,name=skip_checksum,json=skipChecksum" json:"skip_checksum,omitempty"`
	U2FCounter           *uint32     `protobuf:"varint,8,opt,name=u2f_counter,json=u2fCounter" json:"u2f_counter,omitempty"`
	XXX_unrecognized     []byte      `json:"-"`
}

func (m *LoadDevice) Reset()                    { *m = LoadDevice{} }
func (m *LoadDevice) String() string            { return proto.CompactTextString(m) }
func (*LoadDevice) ProtoMessage()               {}
func (*LoadDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

const Default_LoadDevice_Language string = "english"

func (m *LoadDevice) GetMnemonic() string {
	if m != nil && m.Mnemonic != nil {
		return *m.Mnemonic
	}
	return ""
}

func (m *LoadDevice) GetNode() *HDNodeType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *LoadDevice) GetPin() string {
	if m != nil && m.Pin != nil {
		return *m.Pin
	}
	return ""
}

func (m *LoadDevice) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

func (m *LoadDevice) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return Default_LoadDevice_Language
}

func (m *LoadDevice) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *LoadDevice) GetSkipChecksum() bool {
	if m != nil && m.SkipChecksum != nil {
		return *m.SkipChecksum
	}
	return false
}

func (m *LoadDevice) GetU2FCounter() uint32 {
	if m != nil && m.U2FCounter != nil {
		return *m.U2FCounter
	}
	return 0
}

// *
// Request: Ask device to do initialization involving user interaction
// @next EntropyRequest
// @next Failure
type ResetDevice struct {
	DisplayRandom        *bool   `protobuf:"varint,1,opt,name=display_random,json=displayRandom" json:"display_random,omitempty"`
	Strength             *uint32 `protobuf:"varint,2,opt,name=strength,def=256" json:"strength,omitempty"`
	PassphraseProtection *bool   `protobuf:"varint,3,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	PinProtection        *bool   `protobuf:"varint,4,opt,name=pin_protection,json=pinProtection" json:"pin_protection,omitempty"`
	Language             *string `protobuf:"bytes,5,opt,name=language,def=english" json:"language,omitempty"`
	Label                *string `protobuf:"bytes,6,opt,name=label" json:"label,omitempty"`
	U2FCounter           *uint32 `protobuf:"varint,7,opt,name=u2f_counter,json=u2fCounter" json:"u2f_counter,omitempty"`
	SkipBackup           *bool   `protobuf:"varint,8,opt,name=skip_backup,json=skipBackup" json:"skip_backup,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *ResetDevice) Reset()                    { *m = ResetDevice{} }
func (m *ResetDevice) String() string            { return proto.CompactTextString(m) }
func (*ResetDevice) ProtoMessage()               {}
func (*ResetDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

const Default_ResetDevice_Strength uint32 = 256
const Default_ResetDevice_Language string = "english"

func (m *ResetDevice) GetDisplayRandom() bool {
	if m != nil && m.DisplayRandom != nil {
		return *m.DisplayRandom
	}
	return false
}

func (m *ResetDevice) GetStrength() uint32 {
	if m != nil && m.Strength != nil {
		return *m.Strength
	}
	return Default_ResetDevice_Strength
}

func (m *ResetDevice) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

func (m *ResetDevice) GetPinProtection() bool {
	if m != nil && m.PinProtection != nil {
		return *m.PinProtection
	}
	return false
}

func (m *ResetDevice) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return Default_ResetDevice_Language
}

func (m *ResetDevice) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *ResetDevice) GetU2FCounter() uint32 {
	if m != nil && m.U2FCounter != nil {
		return *m.U2FCounter
	}
	return 0
}

func (m *ResetDevice) GetSkipBackup() bool {
	if m != nil && m.SkipBackup != nil {
		return *m.SkipBackup
	}
	return false
}

// *
// Request: Perform backup of the device seed if not backed up using ResetDevice
// @next ButtonRequest
type BackupDevice struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BackupDevice) Reset()                    { *m = BackupDevice{} }
func (m *BackupDevice) String() string            { return proto.CompactTextString(m) }
func (*BackupDevice) ProtoMessage()               {}
func (*BackupDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

// *
// Response: Ask for additional entropy from host computer
// @prev ResetDevice
// @next EntropyAck
type EntropyRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EntropyRequest) Reset()                    { *m = EntropyRequest{} }
func (m *EntropyRequest) String() string            { return proto.CompactTextString(m) }
func (*EntropyRequest) ProtoMessage()               {}
func (*EntropyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

// *
// Request: Provide additional entropy for seed generation function
// @prev EntropyRequest
// @next ButtonRequest
type EntropyAck struct {
	Entropy          []byte `protobuf:"bytes,1,opt,name=entropy" json:"entropy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EntropyAck) Reset()                    { *m = EntropyAck{} }
func (m *EntropyAck) String() string            { return proto.CompactTextString(m) }
func (*EntropyAck) ProtoMessage()               {}
func (*EntropyAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *EntropyAck) GetEntropy() []byte {
	if m != nil {
		return m.Entropy
	}
	return nil
}

func init() {
	proto.RegisterType((*Initialize)(nil), "Initialize")
	proto.RegisterType((*GetFeatures)(nil), "GetFeatures")
	proto.RegisterType((*Features)(nil), "Features")
	proto.RegisterType((*SetMnemonic)(nil), "SetMnemonic")
	proto.RegisterType((*ChangePin)(nil), "ChangePin")
	proto.RegisterType((*SkycoinAddress)(nil), "SkycoinAddress")
	proto.RegisterType((*ResponseSkycoinAddress)(nil), "ResponseSkycoinAddress")
	proto.RegisterType((*SkycoinCheckMessageSignature)(nil), "SkycoinCheckMessageSignature")
	proto.RegisterType((*SkycoinSignMessage)(nil), "SkycoinSignMessage")
	proto.RegisterType((*Ping)(nil), "Ping")
	proto.RegisterType((*Success)(nil), "Success")
	proto.RegisterType((*Failure)(nil), "Failure")
	proto.RegisterType((*ButtonRequest)(nil), "ButtonRequest")
	proto.RegisterType((*ButtonAck)(nil), "ButtonAck")
	proto.RegisterType((*PinMatrixRequest)(nil), "PinMatrixRequest")
	proto.RegisterType((*PinMatrixAck)(nil), "PinMatrixAck")
	proto.RegisterType((*Cancel)(nil), "Cancel")
	proto.RegisterType((*PassphraseRequest)(nil), "PassphraseRequest")
	proto.RegisterType((*PassphraseAck)(nil), "PassphraseAck")
	proto.RegisterType((*PassphraseStateRequest)(nil), "PassphraseStateRequest")
	proto.RegisterType((*PassphraseStateAck)(nil), "PassphraseStateAck")
	proto.RegisterType((*GetEntropy)(nil), "GetEntropy")
	proto.RegisterType((*Entropy)(nil), "Entropy")
	proto.RegisterType((*WipeDevice)(nil), "WipeDevice")
	proto.RegisterType((*LoadDevice)(nil), "LoadDevice")
	proto.RegisterType((*ResetDevice)(nil), "ResetDevice")
	proto.RegisterType((*BackupDevice)(nil), "BackupDevice")
	proto.RegisterType((*EntropyRequest)(nil), "EntropyRequest")
	proto.RegisterType((*EntropyAck)(nil), "EntropyAck")
	proto.RegisterEnum("MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xcb, 0x6e, 0x1b, 0x37,
	0x17, 0xfe, 0x75, 0xb1, 0x25, 0x1d, 0x5d, 0x42, 0xd3, 0x97, 0x4c, 0x64, 0x27, 0x56, 0x46, 0xb9,
	0xd8, 0x49, 0x20, 0xfc, 0x50, 0xdb, 0x2c, 0x02, 0x74, 0x61, 0x3b, 0x57, 0xa4, 0x0e, 0x0c, 0x39,
	0x48, 0x97, 0x02, 0x3d, 0x43, 0x49, 0xac, 0x24, 0xce, 0x64, 0x38, 0xb2, 0xab, 0x3c, 0x45, 0xba,
	0x6b, 0x1f, 0xa1, 0x9b, 0xa2, 0x9b, 0xbe, 0x5f, 0xc1, 0xcb, 0x68, 0x38, 0x8a, 0x1c, 0xa0, 0xed,
	0x8e, 0xe7, 0x3b, 0xdf, 0x9c, 0x43, 0x7e, 0x3c, 0x3c, 0xe4, 0x40, 0x63, 0x4a, 0x85, 0x20, 0x43,
	0x2a, 0x3a, 0x61, 0x14, 0xc4, 0x41, 0xb3, 0x1a, 0xcf, 0xc3, 0xc4, 0x70, 0x5d, 0x80, 0x37, 0x9c,
	0xc5, 0x8c, 0x4c, 0xd8, 0x27, 0x8a, 0xb7, 0x60, 0x4d, 0xc4, 0x24, 0xa6, 0x4e, 0xae, 0x95, 0x3b,
	0xa8, 0xf5, 0xb4, 0xe1, 0xd6, 0xa1, 0xfa, 0x8a, 0xc6, 0x2f, 0x29, 0x89, 0x67, 0x11, 0x15, 0xee,
	0xe7, 0x12, 0x94, 0x13, 0x03, 0xef, 0xc0, 0xfa, 0x25, 0xe5, 0x7e, 0x10, 0xa9, 0x4f, 0x2a, 0x3d,
	0x63, 0xe1, 0x36, 0xd4, 0xa7, 0xe4, 0xa7, 0x20, 0xea, 0x5f, 0xd2, 0x48, 0xb0, 0x80, 0x3b, 0xf9,
	0x56, 0xee, 0xa0, 0xde, 0xab, 0x29, 0xf0, 0x83, 0xc6, 0x14, 0x89, 0x71, 0x8b, 0x54, 0x30, 0x24,
	0x09, 0x5a, 0xa4, 0x90, 0xc4, 0xde, 0x68, 0x41, 0x2a, 0x6a, 0x92, 0x02, 0x13, 0xd2, 0x43, 0xb8,
	0x71, 0x11, 0x04, 0xf1, 0x24, 0x20, 0x3e, 0x8d, 0xfa, 0xd3, 0xc0, 0xa7, 0xce, 0x5a, 0x2b, 0x77,
	0x50, 0xee, 0x35, 0x52, 0xf8, 0x34, 0xf0, 0x29, 0xde, 0x85, 0x8a, 0x4f, 0x2f, 0x99, 0x47, 0xfb,
	0xcc, 0x77, 0xd6, 0xd5, 0x94, 0xcb, 0x1a, 0x78, 0xe3, 0xe3, 0xfb, 0xd0, 0x08, 0x19, 0xef, 0x4b,
	0x65, 0xa8, 0x17, 0xcb, 0x5c, 0x25, 0x15, 0xa4, 0x1e, 0x32, 0x7e, 0xb6, 0x00, 0xf1, 0x37, 0xb0,
	0x1d, 0x12, 0x21, 0xc2, 0x51, 0x44, 0x04, 0xb5, 0xd9, 0x65, 0xc5, 0xde, 0x4a, 0x9d, 0xd6, 0x47,
	0x4d, 0x28, 0x4f, 0x08, 0x1f, 0xce, 0xc8, 0x90, 0x3a, 0x15, 0x9d, 0x37, 0xb1, 0xa5, 0xec, 0x13,
	0x72, 0x41, 0x27, 0x0e, 0x28, 0x87, 0x36, 0xf0, 0x3e, 0xac, 0x79, 0x01, 0xe3, 0xc2, 0xa9, 0xb6,
	0x0a, 0x07, 0xd5, 0x6e, 0xa5, 0x73, 0x12, 0x30, 0xfe, 0x7e, 0x1e, 0xd2, 0x9e, 0xc6, 0x71, 0x0b,
	0xaa, 0x6c, 0xb1, 0x77, 0xbe, 0x53, 0x53, 0xd9, 0x6d, 0x48, 0x26, 0x8d, 0xe8, 0x25, 0x53, 0xb2,
	0xd5, 0xd5, 0x96, 0x2e, 0xec, 0x25, 0xc9, 0x46, 0x44, 0x8c, 0x9c, 0x86, 0xa2, 0x58, 0x92, 0xbd,
	0x26, 0x62, 0x24, 0x83, 0xb0, 0x69, 0x18, 0x44, 0x31, 0xf5, 0x9d, 0x1b, 0x2a, 0xc7, 0xc2, 0xc6,
	0xb7, 0x01, 0xa4, 0x62, 0x1e, 0xf1, 0x46, 0xd4, 0x77, 0x90, 0xf2, 0x56, 0x42, 0xc6, 0x4f, 0x14,
	0x80, 0x1f, 0xc3, 0x86, 0xa5, 0x94, 0x61, 0x6d, 0x28, 0x16, 0x4a, 0x1d, 0x86, 0x7c, 0x08, 0x68,
	0xc0, 0xa2, 0xe9, 0x15, 0x89, 0xa4, 0xa8, 0x54, 0x50, 0x1e, 0x3b, 0x58, 0x71, 0x6f, 0x24, 0xf8,
	0x99, 0x86, 0xf1, 0x5d, 0xa8, 0x71, 0x4a, 0x7d, 0xd1, 0xbf, 0x20, 0xde, 0x78, 0x16, 0x3a, 0x9b,
	0x7a, 0xe9, 0x0a, 0x3b, 0x56, 0x90, 0xd4, 0x74, 0x30, 0x21, 0x43, 0xe1, 0x6c, 0xa9, 0x72, 0xd1,
	0x86, 0x44, 0x65, 0x71, 0x4c, 0x9c, 0x6d, 0xad, 0xb4, 0x32, 0xf0, 0x2d, 0x28, 0x0f, 0xae, 0xfa,
	0xaa, 0x34, 0x9d, 0x1d, 0x45, 0x2f, 0x0d, 0xae, 0x4e, 0xa5, 0x99, 0xb8, 0x64, 0x41, 0x3a, 0x37,
	0x17, 0x2e, 0x69, 0x1a, 0x97, 0x2a, 0x43, 0xc7, 0x49, 0x5c, 0x67, 0xd2, 0x94, 0x55, 0x36, 0xb8,
	0xea, 0x9b, 0x83, 0x71, 0x4b, 0xef, 0xf6, 0xe0, 0xea, 0x83, 0x3e, 0x1a, 0xf7, 0xa0, 0xb1, 0x70,
	0xf6, 0xc7, 0x74, 0x2e, 0x9c, 0xa6, 0xd2, 0xbd, 0x96, 0x30, 0xde, 0xd2, 0xb9, 0x90, 0xd2, 0xcd,
	0xf8, 0x80, 0x71, 0x26, 0x46, 0xd4, 0x4f, 0xd6, 0xb9, 0xab, 0xa5, 0x4b, 0x1d, 0x7a, 0xb1, 0xee,
	0x21, 0x54, 0xcf, 0x69, 0x7c, 0xca, 0xe9, 0x34, 0xe0, 0xcc, 0x93, 0x3b, 0x36, 0x35, 0x63, 0x27,
	0xd7, 0xca, 0xcb, 0xec, 0x89, 0xed, 0xb6, 0xa1, 0x72, 0x32, 0x22, 0x7c, 0x48, 0xcf, 0x18, 0x97,
	0xa7, 0x37, 0xa2, 0xd3, 0xe0, 0x52, 0x1f, 0xf8, 0x72, 0xcf, 0x58, 0x2e, 0x85, 0xc6, 0xf9, 0x78,
	0x2e, 0xab, 0xec, 0xc8, 0xf7, 0x23, 0x2a, 0x84, 0x5c, 0x11, 0xd1, 0xc3, 0x3e, 0x57, 0x31, 0xeb,
	0xbd, 0xb2, 0x01, 0xde, 0xe1, 0xa7, 0x50, 0x4b, 0x9c, 0xb2, 0xb7, 0xa8, 0xb3, 0xde, 0xe8, 0x6e,
	0x76, 0xb2, 0x31, 0x54, 0xe9, 0x56, 0x49, 0x6a, 0xb8, 0x5d, 0xd8, 0xe9, 0x51, 0x11, 0x06, 0x5c,
	0xd0, 0xa5, 0x74, 0x0e, 0x94, 0x0c, 0xd1, 0x2c, 0x20, 0x31, 0xdd, 0x10, 0xf6, 0x0c, 0xf7, 0x64,
	0x44, 0xbd, 0xf1, 0xa9, 0xee, 0x6d, 0xe7, 0x6c, 0xc8, 0x55, 0x47, 0xba, 0xfe, 0x4b, 0xe9, 0x31,
	0x9d, 0xd0, 0xc9, 0x6b, 0x8f, 0x31, 0xf1, 0x1e, 0x54, 0x44, 0x12, 0xc0, 0x29, 0x28, 0x5f, 0x0a,
	0xb8, 0x6f, 0x01, 0x9b, 0x8c, 0x32, 0x8b, 0x49, 0xf8, 0x75, 0x41, 0xae, 0x4d, 0xe5, 0xfe, 0x9e,
	0x83, 0xe2, 0x19, 0xe3, 0x43, 0x9b, 0xa2, 0x3b, 0xe7, 0x62, 0x36, 0x8f, 0x61, 0xe3, 0x62, 0x16,
	0xc7, 0x41, 0xa6, 0x11, 0xe5, 0xf5, 0xce, 0x6b, 0x87, 0xd5, 0x56, 0xbe, 0x6c, 0x59, 0x85, 0x7f,
	0xd4, 0xb2, 0x8a, 0xd7, 0xb7, 0x2c, 0xb7, 0x0d, 0xa5, 0xf3, 0x99, 0xe7, 0x2d, 0x69, 0x97, 0x9d,
	0xad, 0xfb, 0x02, 0x4a, 0x2f, 0x09, 0x9b, 0x48, 0xe9, 0x5b, 0x50, 0xf4, 0x64, 0xe7, 0xcd, 0xa9,
	0xed, 0xaf, 0x75, 0x0c, 0xae, 0xf6, 0x5d, 0x79, 0xb2, 0xba, 0x64, 0xc2, 0xbc, 0x85, 0xfa, 0xb1,
	0x5a, 0x5b, 0x8f, 0x7e, 0x9c, 0x51, 0x11, 0xe3, 0x07, 0x99, 0x60, 0xb8, 0x93, 0xf1, 0x5a, 0x21,
	0x31, 0x14, 0x7d, 0x12, 0x13, 0x13, 0x4f, 0x8d, 0xdd, 0x2a, 0x54, 0x34, 0xfd, 0xc8, 0x1b, 0xbb,
	0xdf, 0x03, 0x3a, 0x63, 0xfc, 0x94, 0xc4, 0x11, 0xfb, 0x39, 0x09, 0x7e, 0x08, 0x45, 0x55, 0xa8,
	0x3a, 0xf8, 0x76, 0x67, 0x99, 0xa0, 0xe3, 0x4b, 0x8a, 0xdb, 0x82, 0xda, 0xc2, 0x7b, 0xe4, 0x8d,
	0x31, 0x82, 0x42, 0xc8, 0xb8, 0xa9, 0x2d, 0x39, 0x74, 0xcb, 0xb0, 0x7e, 0x42, 0xb8, 0x47, 0x27,
	0xee, 0xff, 0x61, 0xe3, 0x6c, 0x21, 0x64, 0x92, 0x6b, 0x17, 0x2a, 0x01, 0xef, 0xeb, 0x3b, 0xc6,
	0x1c, 0xb3, 0x72, 0xc0, 0x9f, 0x2b, 0xdb, 0x7d, 0x01, 0xf5, 0xf4, 0x0b, 0x19, 0xfe, 0x0e, 0x40,
	0xba, 0x17, 0x46, 0x6b, 0x0b, 0x49, 0x6f, 0xe8, 0xbc, 0x7d, 0x43, 0x77, 0x60, 0x27, 0x0d, 0x73,
	0x2e, 0xa1, 0x24, 0xfb, 0xea, 0x1b, 0x7d, 0x0b, 0xf0, 0x12, 0x5f, 0x2a, 0xd5, 0x02, 0x78, 0x45,
	0xe3, 0x17, 0x3c, 0x8e, 0x82, 0x70, 0x2e, 0x85, 0x15, 0xec, 0x13, 0x35, 0xb5, 0xad, 0xc6, 0xb2,
	0x22, 0x12, 0xb7, 0x03, 0x25, 0xaa, 0x87, 0x8a, 0x51, 0xeb, 0x25, 0xa6, 0x5b, 0x03, 0xf8, 0x91,
	0x85, 0xd4, 0xac, 0xf0, 0x97, 0x3c, 0xc0, 0x0f, 0x01, 0xf1, 0xb5, 0xb9, 0xd4, 0x9a, 0x72, 0x76,
	0x6b, 0xc2, 0xfb, 0x50, 0xe4, 0x72, 0xcb, 0xe5, 0xd2, 0xaa, 0xdd, 0x6a, 0xe7, 0xf5, 0xf3, 0x77,
	0x81, 0x6f, 0xca, 0x47, 0x3a, 0x12, 0xed, 0x0b, 0xea, 0x3b, 0x39, 0xfc, 0x57, 0x75, 0x8d, 0xdb,
	0xd6, 0x55, 0x2c, 0x5f, 0x09, 0x95, 0x67, 0x25, 0xca, 0x87, 0x13, 0x26, 0x46, 0xab, 0xee, 0xe4,
	0x75, 0xfb, 0x4e, 0x6e, 0x43, 0x5d, 0x8c, 0x59, 0xd8, 0xf7, 0x64, 0xef, 0x11, 0xb3, 0xa9, 0x79,
	0x20, 0xd4, 0x24, 0x78, 0x62, 0x30, 0xbc, 0x0f, 0xd5, 0x59, 0x77, 0xd0, 0xf7, 0x82, 0x19, 0x8f,
	0x69, 0xa4, 0x5e, 0x05, 0xf5, 0x1e, 0xcc, 0xba, 0x83, 0x13, 0x8d, 0xb8, 0x7f, 0xe4, 0xa1, 0xda,
	0xa3, 0x82, 0xc6, 0x46, 0x94, 0xfb, 0xd0, 0xf0, 0x99, 0x08, 0x27, 0x64, 0xde, 0x8f, 0x08, 0xf7,
	0x83, 0xa9, 0xa9, 0x93, 0xba, 0x41, 0x7b, 0x0a, 0xc4, 0xfb, 0x50, 0x16, 0x71, 0x44, 0xf9, 0x30,
	0x1e, 0xe9, 0xe7, 0xd4, 0xb3, 0x42, 0xf7, 0xbb, 0xa7, 0xbd, 0x05, 0x78, 0xbd, 0x1a, 0x85, 0xaf,
	0xa8, 0xf1, 0x65, 0x07, 0x29, 0xae, 0xea, 0x20, 0xff, 0x41, 0xb4, 0x25, 0x3d, 0x4a, 0xcb, 0x7a,
	0x48, 0x82, 0x52, 0xd5, 0xdc, 0x72, 0xfa, 0x19, 0x05, 0x12, 0x32, 0xf7, 0x5b, 0x03, 0x6a, 0x7a,
	0x64, 0x8a, 0x0a, 0x41, 0xc3, 0xd4, 0xa1, 0xa9, 0x73, 0xf7, 0x01, 0x80, 0x41, 0xe4, 0x29, 0xca,
	0x14, 0x67, 0xce, 0x2a, 0xce, 0x47, 0xbf, 0x95, 0xa1, 0x6a, 0x5a, 0xb8, 0x2c, 0x2c, 0xdc, 0x82,
	0x1d, 0xcb, 0xec, 0xa7, 0x6f, 0x61, 0xf4, 0xbf, 0x66, 0xf1, 0xf3, 0x5f, 0x4e, 0x0e, 0x37, 0x01,
	0xd9, 0x0c, 0xd9, 0xbc, 0x51, 0xce, 0xf8, 0x6e, 0xc3, 0xa6, 0xed, 0x33, 0xdd, 0x12, 0xe5, 0x9b,
	0xc5, 0x5f, 0x57, 0xb8, 0x4d, 0x3f, 0x44, 0x05, 0xe3, 0xde, 0x87, 0x6d, 0xdb, 0xbd, 0xb8, 0x96,
	0x51, 0xd1, 0x84, 0x5f, 0x9a, 0x5c, 0x7a, 0xaa, 0xd0, 0xda, 0x6a, 0x46, 0x7a, 0x7c, 0x51, 0x65,
	0xf5, 0x14, 0x13, 0x37, 0x98, 0x39, 0x2c, 0x05, 0x48, 0x4f, 0x2a, 0xaa, 0x9b, 0x00, 0x77, 0xe1,
	0xa6, 0xcd, 0xb0, 0xea, 0x16, 0x35, 0x0c, 0xe5, 0x0e, 0x6c, 0x65, 0xd6, 0x69, 0x7e, 0x0e, 0xd0,
	0x86, 0x49, 0xf2, 0x00, 0xf6, 0x96, 0x24, 0xcc, 0x74, 0x5b, 0x84, 0x17, 0x3c, 0x67, 0x25, 0xef,
	0xc8, 0x1b, 0xa3, 0xcd, 0x66, 0x59, 0xe6, 0xfa, 0x53, 0xf2, 0xf6, 0x00, 0x67, 0x84, 0x53, 0xdd,
	0x17, 0x6d, 0x99, 0xd9, 0xb4, 0xe1, 0x96, 0xed, 0xcd, 0x5c, 0x1c, 0xa8, 0x69, 0x52, 0xb5, 0xb3,
	0xda, 0x2f, 0xae, 0x0b, 0xb4, 0x6b, 0xe5, 0x71, 0xb3, 0xf3, 0xb1, 0x4b, 0x10, 0xb9, 0x26, 0xdb,
	0x3d, 0x68, 0xae, 0xd0, 0x37, 0x49, 0xd7, 0x5e, 0x2d, 0x73, 0x5a, 0xaa, 0xe8, 0x9e, 0x89, 0xf3,
	0x10, 0x6e, 0x67, 0xd6, 0xbe, 0x7c, 0x8f, 0xa0, 0x43, 0x13, 0xea, 0x61, 0x76, 0x79, 0x99, 0xeb,
	0x03, 0x3d, 0xb2, 0x66, 0xff, 0x04, 0xdc, 0xd5, 0x44, 0xfb, 0x82, 0x40, 0xa7, 0x26, 0xec, 0x13,
	0xb8, 0xf3, 0x15, 0xb6, 0x8c, 0xfd, 0xce, 0x8a, 0xbd, 0x54, 0x14, 0xd6, 0xe3, 0x13, 0x7d, 0x5c,
	0x2d, 0x4c, 0xf6, 0x81, 0x87, 0x22, 0xc3, 0xea, 0xc2, 0xc1, 0x0a, 0xd6, 0xca, 0xa7, 0x1d, 0x12,
	0xe6, 0x9b, 0x83, 0xec, 0x54, 0xbf, 0x7c, 0x9c, 0xa1, 0xd8, 0x30, 0x97, 0x24, 0x58, 0xfd, 0xd8,
	0x44, 0x33, 0x2d, 0xc1, 0xf1, 0xb7, 0xd0, 0xf6, 0x82, 0x69, 0x47, 0x90, 0x38, 0x10, 0x23, 0x36,
	0x21, 0x17, 0xa2, 0x13, 0x47, 0xf4, 0x53, 0x10, 0x75, 0x26, 0xec, 0x42, 0xff, 0x2f, 0x5f, 0xcc,
	0x06, 0xc7, 0xf5, 0xf7, 0x0a, 0x34, 0x81, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xec, 0x88, 0x08,
	0x9b, 0x5f, 0x0f, 0x00, 0x00,
}
