#!/bin/bash

# This are the git ENV vars present at this point for the build process.
# more on that in https://docs.docker.com/docker-cloud/builds/advanced
# 
# SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
# SOURCE_COMMIT: the SHA1 hash of the commit being tested.
# COMMIT_MSG: the message from the commit being tested and built.
# DOCKERFILE_PATH: the dockerfile currently being built.
# DOCKER_REPO: the name of the Docker repository being built.
# CACHE_TAG: the Docker repository tag being built.
# IMAGE_NAME: the name and tag of the Docker repository being built. 
#             (This variable is a combination of DOCKER_REPO:CACHE_TAG.)

echo "Build hook running"

docker build --build-arg BDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg SCOMMIT=$SOURCE_COMMIT \
             -f $DOCKERFILE_PATH \
             -t "$IMAGE_NAME" .

