// Code generated by github.com/skycoin/skyencoder. DO NOT EDIT.
package daemon

import (
	"errors"
	"math"

	"github.com/skycoin/skycoin/src/cipher/encoder"
)

// EncodeSizeIntroductionMessage computes the size of an encoded object of type IntroductionMessage
func EncodeSizeIntroductionMessage(obj *IntroductionMessage) int {
	i0 := 0

	// obj.Mirror
	i0 += 4

	// obj.ListenPort
	i0 += 2

	// obj.ProtocolVersion
	i0 += 4

	// omitempty
	if len(obj.Extra) != 0 {

		// obj.Extra
		i0 += 4 + len(obj.Extra)

	}

	return i0
}

// EncodeIntroductionMessage encodes an object of type IntroductionMessage to the buffer in encoder.Encoder.
// The buffer must be large enough to encode the object, otherwise an error is returned.
func EncodeIntroductionMessage(buf []byte, obj *IntroductionMessage) error {
	e := &encoder.Encoder{
		Buffer: buf[:],
	}

	// obj.Mirror
	e.Uint32(obj.Mirror)

	// obj.ListenPort
	e.Uint16(obj.ListenPort)

	// obj.ProtocolVersion
	e.Int32(obj.ProtocolVersion)

	// omitempty
	if len(obj.Extra) != 0 {

		// obj.Extra length check
		if len(obj.Extra) > math.MaxUint32 {
			return errors.New("obj.Extra length exceeds math.MaxUint32")
		}

		// obj.Extra length
		e.Uint32(uint32(len(obj.Extra)))

		// obj.Extra copy
		e.CopyBytes(obj.Extra)

	}

	return nil
}

// DecodeIntroductionMessage decodes an object of type IntroductionMessage from the buffer in encoder.Decoder.
// Returns the number of bytes used from the buffer to decode the object.
func DecodeIntroductionMessage(buf []byte, obj *IntroductionMessage) (int, error) {
	d := &encoder.Decoder{
		Buffer: buf[:],
	}

	{
		// obj.Mirror
		i, err := d.Uint32()
		if err != nil {
			return len(buf) - len(d.Buffer), err
		}
		obj.Mirror = i
	}

	{
		// obj.ListenPort
		i, err := d.Uint16()
		if err != nil {
			return len(buf) - len(d.Buffer), err
		}
		obj.ListenPort = i
	}

	{
		// obj.ProtocolVersion
		i, err := d.Int32()
		if err != nil {
			return len(buf) - len(d.Buffer), err
		}
		obj.ProtocolVersion = i
	}

	{
		// obj.Extra

		if len(d.Buffer) == 0 {
			return len(buf) - len(d.Buffer), nil
		}

		ul, err := d.Uint32()
		if err != nil {
			return len(buf) - len(d.Buffer), err
		}

		length := int(ul)
		if length < 0 || length > len(d.Buffer) {
			return len(buf) - len(d.Buffer), encoder.ErrBufferUnderflow
		}

		if length != 0 {
			obj.Extra = make([]byte, length)

			copy(obj.Extra[:], d.Buffer[:length])
			d.Buffer = d.Buffer[length:]
		}
	}

	return len(buf) - len(d.Buffer), nil
}
