// Code generated by github.com/SkycoinProject/skyencoder. DO NOT EDIT.

package daemon

import "github.com/SkycoinProject/skycoin/src/cipher/encoder"

// encodeSizeIPAddr computes the size of an encoded object of type IPAddr
func encodeSizeIPAddr(obj *IPAddr) uint64 {
	i0 := uint64(0)

	// obj.IP
	i0 += 4

	// obj.Port
	i0 += 2

	return i0
}

// encodeIPAddr encodes an object of type IPAddr to a buffer allocated to the exact size
// required to encode the object.
func encodeIPAddr(obj *IPAddr) ([]byte, error) {
	n := encodeSizeIPAddr(obj)
	buf := make([]byte, n)

	if err := encodeIPAddrToBuffer(buf, obj); err != nil {
		return nil, err
	}

	return buf, nil
}

// encodeIPAddrToBuffer encodes an object of type IPAddr to a []byte buffer.
// The buffer must be large enough to encode the object, otherwise an error is returned.
func encodeIPAddrToBuffer(buf []byte, obj *IPAddr) error {
	if uint64(len(buf)) < encodeSizeIPAddr(obj) {
		return encoder.ErrBufferUnderflow
	}

	e := &encoder.Encoder{
		Buffer: buf[:],
	}

	// obj.IP
	e.Uint32(obj.IP)

	// obj.Port
	e.Uint16(obj.Port)

	return nil
}

// decodeIPAddr decodes an object of type IPAddr from a buffer.
// Returns the number of bytes used from the buffer to decode the object.
// If the buffer not long enough to decode the object, returns encoder.ErrBufferUnderflow.
func decodeIPAddr(buf []byte, obj *IPAddr) (uint64, error) {
	d := &encoder.Decoder{
		Buffer: buf[:],
	}

	{
		// obj.IP
		i, err := d.Uint32()
		if err != nil {
			return 0, err
		}
		obj.IP = i
	}

	{
		// obj.Port
		i, err := d.Uint16()
		if err != nil {
			return 0, err
		}
		obj.Port = i
	}

	return uint64(len(buf) - len(d.Buffer)), nil
}

// decodeIPAddrExact decodes an object of type IPAddr from a buffer.
// If the buffer not long enough to decode the object, returns encoder.ErrBufferUnderflow.
// If the buffer is longer than required to decode the object, returns encoder.ErrRemainingBytes.
func decodeIPAddrExact(buf []byte, obj *IPAddr) error {
	if n, err := decodeIPAddr(buf, obj); err != nil {
		return err
	} else if n != uint64(len(buf)) {
		return encoder.ErrRemainingBytes
	}

	return nil
}
