#!/bin/bash
docker build -f docker/images/mainnet/Dockerfile -t $IMAGE_NAME ../../../
docker build --build-arg=ARCH=arm --build-arg=GOARM=5 --build-arg=IMAGE_FROM="arm32v5/alpine" -f docker/images/mainnet/Dockerfile -t $IMAGE_NAME-arm32v5 .
docker build --build-arg=ARCH=arm --build-arg=GOARM=6 --build-arg=IMAGE_FROM="arm32v6/alpine" -f docker/images/mainnet/Dockerfile -t $IMAGE_NAME-arm32v6 .
docker build --build-arg=ARCH=arm --build-arg=GOARM=7 --build-arg=IMAGE_FROM="arm32v7/alpine" -f docker/images/mainnet/Dockerfile -t $IMAGE_NAME-arm32v7 .
docker build --build-arg=ARCH=arm64 --build-arg=IMAGE_FROM="arm64v8/alpine" -f docker/images/mainnet/Dockerfile -t $IMAGE_NAME-arm64v8 .
