/*typedef struct{
    GoString_ CurrentSupply;
    GoString_ TotalSupply;
    GoString_ MaxSupply;
    GoString_ CurrentCoinHourSupply;
    GoString_ TotalCoinHourSupply;
    GoSlice_  UnlockedAddresses;
    GoSlice_  LockedAddresses;
} api__CoinSupply;*/
typedef struct{
    visor__Richlist Richlist;
} api__Richlist;
typedef struct{
    visor__TransactionStatus Status;
    GoUint32_ Length;
    GoUint8_ Type;
    GoString_ Hash;
    GoString_ InnerHash;
    GoUint64_ Timestamp;
    GoSlice_  Sigs;
    GoSlice_  In;
    GoSlice_  Out;
} api__ReadableTransaction;
