typedef struct{
    GoString_ Addr;
    GoUint64_ Coins;
} cli__SendAmount;
typedef struct{
    GoString_ Addr;
    GoString_ Coins;
} cli__sendAmountJSON;
typedef struct{
    GoString_ Wallet;
    GoString_ Address;
} cli__walletAddress;
