typedef struct{
    GoString_ Addr;
    BOOL Solicited;
} daemon__ConnectEvent;
typedef struct{
    GoString_ Addr;
    GoInt32_ Error;
} daemon__ConnectionError;
typedef struct{
    GoString_ Addr;
    gnet__DisconnectReason Reason;
} daemon__DisconnectEvent;
