typedef struct{
    BOOL Confirmed;
    BOOL Unconfirmed;
    GoUint64_ Height;
    GoUint64_ BlockSeq;
    BOOL Unknown;
} visor__TransactionStatus;
typedef GoSlice_  visor__ReadableOutputs;
typedef struct{
    GoUint32_ Length;
    GoUint8_ Type;
    GoString_ Hash;
    GoString_ InnerHash;
    GoUint64_ Timestamp;
    GoSlice_  Sigs;
    GoSlice_  In;
    GoSlice_  Out;
} visor__ReadableTransaction;
typedef struct{
    GoUint64_ BkSeq;
    GoString_ BlockHash;
    GoString_ PreviousBlockHash;
    GoUint64_ Time;
    GoUint64_ Fee;
    GoUint32_ Version;
    GoString_ BodyHash;
} visor__ReadableBlockHeader;
typedef struct{
    visor__ReadableOutputs HeadOutputs;
    visor__ReadableOutputs OutgoingOutputs;
    visor__ReadableOutputs IncomingOutputs;
} visor__ReadableOutputSet;
typedef struct{
    coin__Transaction Txn;
    visor__TransactionStatus Status;
    GoUint64_ Time;
    GoInt_ Size;
} visor__Transaction;
