name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Test:
    name: Do ${{ matrix.test }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [units, integrations, integrations/disable-csrf, integrations/auth]
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'npm'
          cache-dependency-path: |
            src/gui/static/package-lock.json
            electron/package-lock.json

      - name: Test
        env:
          TEST_SUIT: ${{ matrix.test }}
        run: |
          Xvfb -ac :99 -screen 0 1280x1024x16 &
          export DISPLAY=:99
          ./ci-scripts/lint-and-test.sh

  Build:
    name: Build wallets
    needs: Test
    runs-on: macos-14
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Gox
        run: go install github.com/skycoin/gox@latest

      - name: Cache Electron dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/electron
            ~/Library/Caches/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('./electron/package-lock.json') }}

      - name: Build Wallets
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: ./ci-scripts/build-wallet.sh
